name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ubuntu-release:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
        fish-release:
          - stock
          - 2
          - 3
        exclude:
          - ubuntu-release: ubuntu-20.04
            fish-release: 2
          - ubuntu-release: ubuntu-latest
            fish-release: 2
    runs-on: ${{ matrix.ubuntu-release }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Fish
        run: FISH_RELEASE=${{ matrix.fish-release }} tools/ci-install-fish.sh

      - name: Install Oh My Fish!
        run: fish bin/install --verbose --offline --noninteractive --yes

      - name: Run tests
        run: |
          tests/run.fish
          pushd pkg/fish-spec; fish -c 'fish-spec'; popd
          pushd pkg/omf; fish -c 'fish-spec'; popd

  notify-success:
    needs: [build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@1304fe59e43bec64c91992ad58399b5e1c6dcd17
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":octocat:"
          SLACK_COLOR: good
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: Build Success
          SLACK_FOOTER: ""

  notify-failure:
    needs: [build]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@1304fe59e43bec64c91992ad58399b5e1c6dcd17
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON_EMOJI: ":octocat:"
          SLACK_COLOR: danger
          SLACK_USERNAME: GitHub Actions
          SLACK_TITLE: Build Failure
          SLACK_FOOTER: ""
